### ISSUE TITLE
BetterChatNames Not Perfect

### ISSUE THREAD

**Issue by Mami-Tomoe** [Break-Ben/BetterDiscordAddons#10]
![a](https://user-images.githubusercontent.com/26508793/198072296-d90c6d38-427c-4996-b39d-e6186350c742.PNG)
On the Friendscord server (https://discord.com/invite/friendscord).

Characters should be fixed if possible.

Thanks.

**Comment by Break-Ben** [comment]
To be completely honest, I don't know if this is worth fixing because it is very much an edge case where only the first letter of each word is one of the hundreds of non-letter letter characters. In a situation like this, I'd usually recommend manually renaming the channels with DevilBro's EditChannels plugin, although to quickly fix your specific issue, you can replace line 17 of the plugin with `const CapitalRegex = new RegExp(/(^\w)|([^a-zA-ZÀ-ɏḀ-ỿ'’ᑫᗯEᖇTYᑌIOᑭᗩᔕᗪᖴGᕼᒍKᒪᘔ᙭ᑕᐯᗷᑎᗰ]\w)/g)`
Maybe if other people report the same issue with different servers I will fully fix it but for now this will do

btw sorry for the kinda late reply, I've been very busy with exams coming up soon
