### ISSUE TITLE
Thread

### ISSUE THREAD

**Issue by FabioTambu** [Break-Ben/BetterDiscordAddons#22]
You could make it work for Threads as well?

**Comment by Break-Ben** [comment]
It was actually an intentional decision by me to not patch thread names as they do not have the same name limitations as normal channels. Since you can already name them with capitals and spaces, I decided to leave their names untouched, especially to avoid things such as uncapitalising acronyms that used to be capitalised. However, when I have more time I may add this as an option I see how it would be good for consistency

**Comment by Break-Ben** [comment]
I've now partially added this as a setting in 4838c8a (1.6.0). It doesn't yet work in all places but it works in most of the main ones including the title bar and chat mentions.
