### ISSUE TITLE
plugin could not be compiled

### ISSUE THREAD

**Issue by MrNyto** [Break-Ben/BetterDiscordAddons#9]
TypeError: Cannot read property 'transitionTo' of undefined
    at eval (betterdiscord://plugins/BetterChatNames.plugin.js:24:55)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at AsyncFunction.<anonymous> (<anonymous>:4:7353)

what does this mean?

**Comment by Break-Ben** [comment]
Hello! I'm aware that my plugin no longer compiles due to a recent discord update that has broken pretty much every part of my plugin (as well as many others). I currently have other priorities that I need to get done first, but I will try to get this fixed as soon as I have time. Sorry for the inconvenience

**Comment by Break-Ben** [comment]
Currently, I believe I have it mostly fixed, but I just need to wait for an update to be pushed to BetterDiscord that allows for patching again before I can test if it actually works

Thanks for your patience

**Comment by Break-Ben** [comment]
The plugin now compiles again in 5b0fde9 (v1.4) on the **currently unreleased** v1.8 of BetterDiscord
Not all of the previous patches are present in this version but they will come when I have free time
